apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-anyconfig-backend
  labels:
    app: k8s-anyconfig-backend
spec:
  # とりあえず2つのpodに設定しておく
  replicas: 2
  selector:
    matchLabels:
      app: k8s-anyconfig-backend
  template:
    metadata:
      labels:
        app: k8s-anyconfig-backend
    spec:
      containers:
        - name: k8s-anyconfig-backend
          # ローカルで作成したイメージを使用
          image: k8s-anyconfig-backend
          # ローカルのイメージを使用するため、imagePullPolicyをIfNotPresentに設定
          imagePullPolicy: IfNotPresent
          # コンテナのポートは8080
          ports:
            - containerPort: 8080