apiVersion: v1
kind: Service
metadata:
  name: k8s-anyconfig-backend
  labels:
    app: k8s-anyconfig-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-anyconfig-backend
  type: NodePort